### ISSUE TITLE
why 

### ISSUE THREAD

**Issue by yangton** [respecting/NitroPerks#1]
NitroPerks has been abandoned. why

**Comment by nunk7** [comment]
I shouldnt have clicked on update, it is now gone :((

**Comment by BlackusPL** [comment]
if you click update i can give old version who work

**Comment by wolfboy5206** [comment]
> 有
plz

**Comment by g2vnn** [comment]
pass that bro

> 
> 
> if you click update i can give old version who work

pass that bro

**Comment by BlueMaxWasTaken** [comment]
> if you click update i can give old version who work

Can I have it pls

**Comment by NoZ-Forex** [comment]
> if you click update i can give old version who work

give me

**Comment by BlackusPL** [comment]
Catch it
[redacted] :trollface:

**Comment by BlackusPL** [comment]
> if you click update i can give old version who work
[redacted] :trollface:

**Comment by ghost** [comment]
You can use [redacted] :trollface: with check for updates already turned off

**Comment by lem6ns** [comment]
huh?
