### ISSUE TITLE
this isn't an april fools joke, it actually works.

### ISSUE THREAD

**Issue by 1x6** [respecting/NitroPerks#1]
gg thx very helpful
![image](https://user-images.githubusercontent.com/44981148/113290076-02fb7000-92e9-11eb-92af-8b9afa4971b3.png)
![image](https://user-images.githubusercontent.com/44981148/113290255-48b83880-92e9-11eb-9d42-54dc4247d925.png)

**Comment by respecting** [comment]
yes 👍
