### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by zqvv** [respecting/NitroPerks#12]
sooo, how exactly do you uninstall this?

**Comment by KNIF** [comment]
Just disable the plugin and delete the file.

**Comment by zqvv** [comment]
I've done that but every time I load discord it keeps restoring the file

**Comment by respecting** [comment]
close discord fully
head over to your `%appdata%\betterdiscord\plugins` folder
delete NitroPerks.plugin.js

if it's still there, go to the plugins tab in discord and press the garbage can with the X on the plugin to uninstall it
