### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by neptune2716** [respecting/NitroPerks#13]
When i use an emoji on a text the link remains visible while the emoji appears at the bottom of the text. (i use the emojis on 40px)(look at the picture below)
Thank you and good luck for this amazing mod!
![image](https://user-images.githubusercontent.com/70444351/114284962-db787600-9a53-11eb-91ae-335c70e274d5.png)
![image](https://user-images.githubusercontent.com/70444351/114285005-24c8c580-9a54-11eb-9b7f-912da8519ae8.png)

**Comment by respecting** [comment]
not a bug
