### ISSUE TITLE
i dont get perks

### ISSUE THREAD

**Issue by KeparYTbcc** [respecting/NitroPerks#15]
![Screenshot_1012](https://user-images.githubusercontent.com/67996155/114463362-5657a300-9bb2-11eb-812d-082e67f2b140.png)
![Screenshot_1013](https://user-images.githubusercontent.com/67996155/114463379-5a83c080-9bb2-11eb-9241-ed6a667faa00.png)

**Comment by Spencer-0003** [comment]
Also having an issue with screensharing at 1080p/60fps https://cdn.discordapp.com/attachments/820950543316549634/831311844660084736/unknown.png

**Comment by respecting** [comment]
![image](https://user-images.githubusercontent.com/62519659/114476582-b3a22300-9bb7-11eb-9fd4-9ce38eed7b2b.png)
screensharing works for me still, same with emotes
![image](https://user-images.githubusercontent.com/62519659/114476612-c157a880-9bb7-11eb-9d20-5956490e0fcb.png)
