### ISSUE TITLE
add 50px for emoji

### ISSUE THREAD

**Issue by lordbaygon** [respecting/NitroPerks#17]
someone already said this but can you please add 50pixel for emojis?

i tried to edit the file so it will resize to 50 but it just doesnt get embed

**Comment by Badinek** [comment]
yes this please

**Comment by respecting** [comment]
discord doesn't allow 50px embed, only 16, 32, 40, 64, 128 and 256 is all i know.

**Comment by lordbaygon** [comment]
> discord doesn't allow 50px embed, only 16, 32, 40, 64, 128 and 256 is all i know.

ohh.....
ok thanks
