### ISSUE TITLE
Goodbye

### ISSUE THREAD

**Issue by MrIDontKNow-hub** [respecting/NitroPerks#2]
Was my favorite plugin, sadly it was abandoned, I see the reasons for this change, but I am still sad to see it go.  I will watch your career with great interest

**Comment by BlackusPL** [comment]
i still have old version who works fine

**Comment by ywaf** [comment]
> 
> 
> i still have old version who works fine

could you email this to me, thanks.

git@leho.dev

**Comment by BlueMaxWasTaken** [comment]
> i still have old version who works fine

Can you email this to me as well?

|| lightningbluemax@gmail.com ||

**Comment by BlackusPL** [comment]
you have
[redacted] :trollface:

**Comment by ghost** [comment]
You can use [redacted] :trollface: with check for updates already turned off

**Comment by MrIDontKNow-hub** [comment]
> You can use [redacted] :trollface: with check for updates already turned off

Thank you very much

**Comment by SwiftSmoothvZ** [comment]
> > i still have old version who works fine
> 
> could you email this to me, thanks.
> 
> [git@leho.dev](mailto:git@leho.dev)

[redacted] :trollface:

**Comment by lem6ns** [comment]
huh?
