### ISSUE TITLE
Emotes links are showed when using 2 emotes on the same line

### ISSUE THREAD

**Issue by Killerhacker200** [respecting/NitroPerks#23]
-When I try to use multiple emotes, things got weird!
 +Problem: - Links are showed
                   - Each emoji needs its own line

 +Screenshot:
                   -I'm trying to write "<emoji> Boneapeti <Emoji> :
![Capture](https://user-images.githubusercontent.com/82769601/115151594-c45f0700-a097-11eb-8df8-c73a9f6b8853.PNG)

**Comment by respecting** [comment]
known

**Comment by Killerhacker200** [comment]
oh i'm sorry. Read the closed issues, should have done that before.
