### ISSUE TITLE
Animated photo

### ISSUE THREAD

**Issue by Arabals** [respecting/NitroPerks#25]
It says its invalid url i use this :https://media.tenor.com/videos/c076fb6140cd91ad9d6049fe730d2149/mp4 what is wrong how to fix it?

**Comment by Tharki-God** [comment]
> It says its invalid url i use this :https://media.tenor.com/videos/c076fb6140cd91ad9d6049fe730d2149/mp4 what is wrong how to fix it?

Maybe cause it's a Link to the Mp4 file. Try Uploading a gif to discord and copying its like

**Comment by Arabals** [comment]
i did gif now still no working

**Comment by Arabals** [comment]
and if i disable it doesnt disable it it just shows black photo not my main
![image](https://user-images.githubusercontent.com/82904001/115502519-b4a11780-a27d-11eb-9267-3cca185c9e5a.png)
![image](https://user-images.githubusercontent.com/82904001/115502533-bb2f8f00-a27d-11eb-8e09-6a78d89ebcc3.png)

**Comment by respecting** [comment]
has to be a direct GIF / png, not some garbage html url
ctrl+r if your pfp is bugged btw
