### ISSUE TITLE
Spotify Listens

### ISSUE THREAD

**Issue by Tharki-God** [respecting/NitroPerks#27]
Till when Can I get [this](https://cdn.discordapp.com/attachments/604315049187606538/834621670689210418/Spotify.js) Enachned Discord Plugin Implemented into NitroPerks?
The Plugin Enables Listen Along feature to your discord even if you don't have nitro

**Comment by respecting** [comment]
make a pr request i am procrastinating

**Comment by Tharki-God** [comment]
> make a pr request i am procrastinating

sir please do it I want to give the plugin to my homie on his birthday
