### ISSUE TITLE
Emoji size doesn't work

### ISSUE THREAD

**Issue by fastasfrick** [respecting/NitroPerks#4]
if u set ur emoji size any number other than 40 it would not show the emoji

**Comment by respecting** [comment]
pushing a fix (dropdown)
use the sizes
16, 20, 32, 40, 48, and 64

**Comment by fastasfrick** [comment]
btw is there any way to disable the emoji without turning off the plugin so i can still use my client sided pfp?

**Comment by respecting** [comment]
> 
> 
> disable the emoji without turning off the plugin so i can still use my client sided pfp

don't understand this, please elaborate
