### ISSUE TITLE
PFP glitched

### ISSUE THREAD

**Issue by Xoeq** [respecting/NitroPerks#6]
Shows client-sided pfp in a DM call / server member list / profile / hovering over server icon, but doesn't show in the voice channel itself (which causes it not to show when using a game overlay).

Also would be cool to add a client-sided discriminator lol

**Comment by ChillCzech** [comment]
+1

**Comment by respecting** [comment]
fix for later me:
`background-image: url("${DiscordAPI.currentUser.discordObject.avatarURL}")`
