### ISSUE TITLE
PFP 

### ISSUE THREAD

**Issue by ChillCzech** [respecting/NitroPerks#7]
Everything is going in perfect order, but when I wanted to change my profile photo to animated (_gif_) it didn't work and instead of uploading a profile photo, I got a **gray color** ?! which only I see. My friends said that they only see the photo I had before the **NitroPerks** plugin, I don't know what to do with it. _(It would like an educational video.)_

**Comment by Xoeq** [comment]
It's client sided + if the pfp is gray try to restart your Discord & make sure you have animated pfp selected

**Comment by respecting** [comment]
don't upload photo, set the clientsided pfp link in settings
